openapi: 3.0.3
info:
  version: 1.0.0
  title: bserg API
  description: bserg API documentation
servers:
  - url: http://localhost:5000/api/v1
    description: local api
tags:
  - name: projects
  - name: sections
paths:
  /project:
    get:
      tags:
        - projects
      summary: get overview of all projects
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/project'
    post:
      tags:
        - projects
      summary: add a project and its details
      requestBody:
        required: true
        content:
            application/json:
            schema:
              $ref: '#/components/schemas/project'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/objectId'
        400:
          description: can't create
  /project/{id}:
    get:
      tags:
        - projects
      summary: get a project and its details with given id
      parameters:
        - name: id
          in: path
          description: project id
          required: true
          schema:
            type: string
            default: 62bdab54a80869d50fbb014c
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/project'
                  - $ref: '#/components/schemas/project_details'
    delete:
      tags:
        - projects
      summary: delete a project and its details with a given id
      parameters:
        - name: id
          in: path
          description: project id
          required: true
          schema:
            type: string
      responses:
        200:
          description: success

    put:
      tags:
        - projects
      summary: update a project fields with a given id
      parameters:
        - name: id
          in: path
          description: project id
          required: true
          schema:
            type: string
            default: 62bdab54a80869d50fbb014c
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project'
      responses:
        200:
          description: success
  /project/{id}/section/{index}:
    post:
      tags:
        - sections
      summary: update a project_details section with given index
      parameters:
        - name: id
          in: path
          description: project id
          required: true
          schema:
            type: string
            default: 62bdab54a80869d50fbb014c
        - name: index
          in: path
          description: section index
          required: true
          schema:
            type: integer
            default: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/section'
      responses:
        200:
          description: success


components:
  schemas:
    objectId:
      type: object
      properties:
        $oid:
          type: string
          default: 62bdab54a80869d50fbb014c
    document:
      type: object
      properties:
        _id:
          $ref: '#/components/schemas/objectId'
        schema_version:
          type: integer
          default: 1

    field:
      properties:
        type:
          type: string
          default: "Text"
        value:
          type: string
          default: "This is the fields values"

    section:
      properties:
        title:
          type: string
          default: "Section Title"
        fields:
          type: array
          items:
            $ref: '#/components/schemas/field'

    project:
      allOf:
        - $ref: '#/components/schemas/document'
        - type: object
          properties:
            schema_version:
              type: integer
            project_details_id:
              type: integer
              default: 62cbdf72397a5e43dda8f44c
            title:
              type: string
              default: BSERG (Vue)
            description:
              type: string
              default: My own personal website, now created in VueJS
            url:
              type: string
              default: bserg
            date:
              type: string
              default: ""


    project_details:
      allOf:
        - $ref: '#/components/schemas/document'
        - type: object
          properties:
            sections:
              type: array
              items:
                $ref: '#/components/schemas/section'